RDKCOM-4221: REFPLTB-2609 : Build errors in rdk-wifi-hal component for RPI4 ...
Reason for change :Observed below errors,
|
../../../../../../../rdkb/components/opensource/ccsp/rdk-wifi-hal/src/wifi_hal_hostapd.c:
In function 'update_security_config':
|
../../../../../../../rdkb/components/opensource/ccsp/rdk-wifi-hal/src/wifi_hal_hostapd.c:469:22:
error: implicit conversion from 'wifi_mfp_cfg_t' to 'enum mfp_options'
[-Werror=enum-conversion]
|   469 |     conf->ieee80211w = sec->mfp;
|       |                      ^
|
../../../../../../../rdkb/components/opensource/ccsp/rdk-wifi-hal/src/wifi_hal_nl80211.c:
In function 'wifi_drv_switch_channel':
|
../../../../../../../rdkb/components/opensource/ccsp/rdk-wifi-hal/src/wifi_hal_nl80211.c:5945:38:
error: format '%d' expects argument of type 'int', but argument 5 has
type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
|  5945 |                 wifi_hal_error_print("%s:%d:
beacon_csa.probe_resp_len=%d csa_c_off_presp=%d\n",
|       |
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|  5946 |                     __func__, __LINE__,
settings->beacon_csa.probe_resp_len, csa_c_off_presp);
|       |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                             |
|       |
size_t {aka long unsigned int}
|
../../../../../../../rdkb/components/opensource/ccsp/rdk-wifi-hal/src/wifi_hal_priv.h:768:83:
note: in definition of macro 'wifi_hal_error_print'
|   768 | #define wifi_hal_error_print(format, ...)
wifi_hal_print(WIFI_HAL_LOG_LVL_ERROR, format, ##__VA_ARGS__)
|       |
^~~~~~
|
../../../../../../../rdkb/components/opensource/ccsp/rdk-wifi-hal/src/wifi_hal_nl80211.c:5945:73:
note: format string is defined here
|  5945 |                 wifi_hal_error_print("%s:%d:
beacon_csa.probe_resp_len=%d csa_c_off_presp=%d\n",
|       |
~^
|       |
|
|       |
int
|       |
%ld
^~~~~~
Test Procedure : Compiled the rdk-wifi-hal component successfully.
Risks : Low
Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

Reason for change: REFPLTB-2609 : Build errors in rdk-wifi-hal component for RPI4 ...
Test Procedure: None.
Risks: Low.
Priority: P1

(cherry picked from commit 93033dec90f3c479821936a2e683dbcfbc347881)
Change-Id: I46a48f98c56a7273845ef85b391bdc824edcc125